apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-api
  namespace: ecommerce
type: Opaque
stringData:
  DB_PASSWORD: "change-me-lab-only-not-for-prod"
  JWT_SECRET: "replace-with-openssl-rand-hex-32-value-here"
  METRICS_TOKEN: "replace-with-openssl-rand-hex-32-value-here"
